/* =========================================================
   pack.js — 기본 단어팩 (영어 팟캐스트 빈출 표현)
   w: 단어 / k: 한글 뜻 / p: 품사 / d: 영어 뜻 / e: 예문
   ========================================================= */
window.STARTER_PACK = {
  folder: '팟캐스트 빈출',
  words: [
    { w: 'figure out', k: '알아내다, 이해하다', p: 'phrasal verb', d: 'to understand or solve something', e: "It took me a while to figure out what he really meant." },
    { w: 'come up with', k: '생각해내다', p: 'phrasal verb', d: 'to think of an idea or plan', e: "She came up with a brilliant idea for the podcast." },
    { w: 'end up', k: '결국 ~하게 되다', p: 'phrasal verb', d: 'to finally be in a particular situation', e: "We ended up talking for three hours." },
    { w: 'turn out', k: '~로 밝혀지다', p: 'phrasal verb', d: 'to happen in a particular way, or to be discovered finally', e: "It turned out that he had been right all along." },
    { w: 'reach out', k: '연락하다, 손을 내밀다', p: 'phrasal verb', d: 'to contact someone, often to offer or ask for help', e: "Feel free to reach out if you have any questions." },
    { w: 'bring up', k: '(화제를) 꺼내다', p: 'phrasal verb', d: 'to start talking about a subject', e: "I hate to bring this up, but we are running out of time." },
    { w: 'take on', k: '떠맡다, 감당하다', p: 'phrasal verb', d: 'to accept a responsibility or task', e: "He took on too many projects at once." },
    { w: 'get rid of', k: '없애다, 처분하다', p: 'phrasal verb', d: 'to remove or throw away something unwanted', e: "I finally got rid of all those old notebooks." },
    { w: 'look into', k: '조사하다, 알아보다', p: 'phrasal verb', d: 'to examine the facts about a problem', e: "We are looking into why the numbers dropped." },
    { w: 'run into', k: '우연히 마주치다', p: 'phrasal verb', d: 'to meet someone by chance', e: "I ran into my old teacher at the bookstore." },
    { w: 'put off', k: '미루다', p: 'phrasal verb', d: 'to delay something until later', e: "Don't put off studying until the night before." },
    { w: 'work out', k: '잘 풀리다; 운동하다', p: 'phrasal verb', d: 'to develop in a successful way, or to exercise', e: "Everything worked out better than we expected." },
    { w: 'pick up on', k: '알아채다', p: 'phrasal verb', d: 'to notice something that is not obvious', e: "She picked up on the tension right away." },
    { w: 'keep up with', k: '뒤처지지 않고 따라가다', p: 'phrasal verb', d: 'to stay at the same level or speed as something', e: "It is hard to keep up with native speakers at first." },
    { w: 'break down', k: '고장 나다; 세부적으로 나누다', p: 'phrasal verb', d: 'to stop working, or to divide into parts', e: "Let me break down the process step by step." },
    { w: 'stand out', k: '두드러지다', p: 'phrasal verb', d: 'to be easily noticed', e: "One thing really stood out in his answer." },
    { w: 'catch up', k: '따라잡다; 근황을 나누다', p: 'phrasal verb', d: 'to reach the same level, or to exchange news', e: "Let's catch up over coffee sometime." },
    { w: 'point out', k: '지적하다, 짚어 주다', p: 'phrasal verb', d: 'to tell someone about a fact', e: "She pointed out a flaw in my argument." },
    { w: 'boil down to', k: '결국 ~로 귀결되다', p: 'phrasal verb', d: 'to have as the main or basic part', e: "It all boils down to how much time you can commit." },
    { w: 'delve into', k: '파고들다, 깊이 탐구하다', p: 'phrasal verb', d: 'to examine something carefully in order to discover more', e: "Today we are going to delve into the history of jazz." },

    { w: 'resilient', k: '회복력 있는, 탄력적인', p: 'adjective', d: 'able to recover quickly from difficulties', e: "Children are surprisingly resilient." },
    { w: 'overwhelming', k: '압도적인, 벅찬', p: 'adjective', d: 'very great or intense; difficult to deal with', e: "The response from listeners was overwhelming." },
    { w: 'straightforward', k: '간단명료한, 솔직한', p: 'adjective', d: 'easy to understand or do; honest', e: "The instructions are pretty straightforward." },
    { w: 'compelling', k: '설득력 있는, 강렬한', p: 'adjective', d: 'so convincing or interesting that it holds attention', e: "She made a compelling case for changing the plan." },
    { w: 'subtle', k: '미묘한, 섬세한', p: 'adjective', d: 'not obvious; delicate', e: "There is a subtle difference between the two words." },
    { w: 'counterintuitive', k: '직관에 반하는', p: 'adjective', d: 'opposite to what you would expect', e: "It sounds counterintuitive, but slowing down helps you learn faster." },
    { w: 'inevitable', k: '불가피한', p: 'adjective', d: 'certain to happen and impossible to avoid', e: "Some mistakes are inevitable when you speak a new language." },
    { w: 'sustainable', k: '지속 가능한', p: 'adjective', d: 'able to continue over a long period', e: "Studying ten minutes a day is more sustainable than cramming." },
    { w: 'ambiguous', k: '모호한, 애매한', p: 'adjective', d: 'having more than one possible meaning', e: "His answer was deliberately ambiguous." },
    { w: 'redundant', k: '불필요하게 중복된', p: 'adjective', d: 'not needed because it is more than what is necessary', e: "That last sentence feels redundant." },

    { w: 'nuance', k: '뉘앙스, 미묘한 차이', p: 'noun', d: 'a very slight difference in meaning or feeling', e: "You start to hear the nuance after months of listening." },
    { w: 'insight', k: '통찰, 이해', p: 'noun', d: 'a clear and deep understanding of something', e: "The interview gave me real insight into how she works." },
    { w: 'perspective', k: '관점, 시각', p: 'noun', d: 'a particular way of thinking about something', e: "Living abroad changed my perspective completely." },
    { w: 'assumption', k: '가정, 추정', p: 'noun', d: 'something you accept as true without proof', e: "We are making a lot of assumptions here." },
    { w: 'framework', k: '틀, 체계', p: 'noun', d: 'a basic structure of ideas or rules', e: "He offers a simple framework for making decisions." },
    { w: 'trade-off', k: '상충 관계, 절충', p: 'noun', d: 'a balance between two things you cannot have at the same time', e: "There is always a trade-off between speed and accuracy." },
    { w: 'takeaway', k: '핵심 교훈, 요점', p: 'noun', d: 'the main message or lesson you learn', e: "The biggest takeaway is that consistency beats intensity." },
    { w: 'setback', k: '차질, 좌절', p: 'noun', d: 'a problem that delays progress', e: "A small setback is not a reason to quit." },
    { w: 'consensus', k: '합의, 의견 일치', p: 'noun', d: 'a general agreement among a group', e: "There is no clear consensus on that question yet." },
    { w: 'game changer', k: '판도를 바꾸는 것', p: 'noun', d: 'something that significantly changes a situation', e: "Shadowing was a total game changer for my pronunciation." },

    { w: 'leverage', k: '활용하다, 지렛대로 삼다', p: 'verb', d: 'to use something to maximum advantage', e: "You can leverage your listening practice to improve speaking." },
    { w: 'underestimate', k: '과소평가하다', p: 'verb', d: 'to think something is smaller or less important than it is', e: "Never underestimate the power of daily review." },
    { w: 'acknowledge', k: '인정하다', p: 'verb', d: 'to accept or admit that something is true', e: "He acknowledged that the first draft was rough." },
    { w: 'emphasize', k: '강조하다', p: 'verb', d: 'to give special importance to something', e: "I want to emphasize how important repetition is." },
    { w: 'tackle', k: '(문제를) 다루다, 씨름하다', p: 'verb', d: 'to make a determined effort to deal with a problem', e: "Let's tackle the hardest words first." },
    { w: 'navigate', k: '헤쳐 나가다', p: 'verb', d: 'to find your way through a difficult situation', e: "Learning to navigate small talk takes practice." },
    { w: 'embrace', k: '받아들이다, 포용하다', p: 'verb', d: 'to accept something willingly', e: "You have to embrace making mistakes." },
    { w: 'thrive', k: '번창하다, 잘 자라다', p: 'verb', d: 'to grow or develop well', e: "Some learners thrive with a strict routine." },
    { w: 'mitigate', k: '완화하다, 줄이다', p: 'verb', d: 'to make something less harmful or serious', e: "Taking notes helps mitigate the frustration of forgetting." },
    { w: 'anticipate', k: '예상하다, 기대하다', p: 'verb', d: 'to expect something to happen', e: "I did not anticipate how fast they would speak." },
    { w: 'articulate', k: '분명히 표현하다', p: 'verb', d: 'to express an idea clearly in words', e: "It is hard to articulate what I mean in English." },
    { w: 'advocate', k: '옹호하다, 지지하다', p: 'verb', d: 'to publicly support an idea or plan', e: "She advocates learning vocabulary in context." },
    { w: 'reinforce', k: '강화하다, 보강하다', p: 'verb', d: 'to make something stronger', e: "Reviewing example sentences reinforces the meaning." },
    { w: 'grasp', k: '이해하다, 파악하다', p: 'verb', d: 'to understand something fully', e: "I finally grasped the difference between the two tenses." },

    { w: 'arguably', k: '거의 틀림없이, 아마도', p: 'adverb', d: 'used when stating an opinion you believe can be defended', e: "This is arguably the best episode of the season." },
    { w: 'essentially', k: '본질적으로, 사실상', p: 'adverb', d: 'in the most basic way; basically', e: "Essentially, it is the same idea in different words." },
    { w: 'presumably', k: '아마도, 짐작하건대', p: 'adverb', d: 'used to say that something is probably true', e: "Presumably, they recorded this before the news broke." },
    { w: 'nonetheless', k: '그럼에도 불구하고', p: 'adverb', d: 'in spite of what has just been said', e: "It was a small change; nonetheless, it made a difference." },
    { w: 'regardless', k: '상관없이', p: 'adverb', d: 'without being affected by something', e: "Keep going regardless of how slow it feels." },
    { w: 'accordingly', k: '그에 맞춰, 따라서', p: 'adverb', d: 'in a way that is appropriate to the situation', e: "The schedule changed, so we adjusted accordingly." },

    { w: 'in a nutshell', k: '요컨대, 한마디로', p: 'idiom', d: 'in the fewest possible words', e: "In a nutshell, listen more than you speak at first." },
    { w: 'long story short', k: '간단히 말하면', p: 'idiom', d: 'used to give only the main point of a story', e: "Long story short, I missed the flight." },
    { w: 'off the top of my head', k: '즉석에서 생각나는 대로', p: 'idiom', d: 'without careful thought or checking', e: "Off the top of my head, I would say about twenty." },
    { w: 'take it with a grain of salt', k: '걸러 듣다', p: 'idiom', d: 'to not completely believe something', e: "Take online rankings with a grain of salt." },
    { w: 'on the fence', k: '결정을 못 내린', p: 'idiom', d: 'undecided between two options', e: "I am still on the fence about which app to use." },
    { w: 'hands down', k: '두말할 나위 없이', p: 'idiom', d: 'without any doubt; easily', e: "That is hands down the most useful tip I have heard." }
  ]
};
